#!/bin/bash
set -e

setup_etc()
{
    mkdir -p /etc /proc
    mount -t tmpfs none /etc
    mount -t proc none /proc
    cp -rfp /usr/etc/* /etc
}

setup_modules()
{
    if [ -e .base/lib/modules/$(uname -r) ]; then
        mount --bind .base/lib/modules /lib/modules
    fi
    if [ -e .base/lib/firmware ]; then
        mount --bind .base/lib/firmware /lib/firmware
    fi
}

setup_users()
{
    sed -i 's!/bin/ash!/bin/bash!' /etc/passwd
    mkdir -p /home
    sed -i 's/^\(sudo:.*\)/\1rancher/g' /etc/group
    addgroup --gid 1000 rancher
    adduser -q --shell /bin/bash --uid 1000 --gid 1000 --disabled-password --gecos "" rancher
    mkdir -p /home/rancher/.kube
    ln -sf /etc/rancher/rke2/rke2.yaml /home/rancher/.kube/config
    chown -R 1000:1000 /home/rancher/.kube
    echo 'rancher:*' | chpasswd -e
}

setup_dirs()
{
    mkdir -p /run/rke2os
    chmod a+rw /dev/null
}

setup_config()
{
    if [ "$RKE2OS_MODE" = "local" ]; then
        return 0
    fi

    $RKE2OS_SYSTEM/rke2os/current/rke2os config --initrd
}

setup_etc

. $SCRIPTS/functions

setup_modules
setup_users
$RKE2OS_SYSTEM/rke2os/current/rke2os rc
setup_dirs
setup_kernel
setup_config

pinfo Bootstrapped
