#!/bin/bash

TARGET=/run/rke2os/target

source /usr/lib/os-release

grow()
{
    parted $1 resizepart $2 100%
    partprobe $1
    sleep 2
    e2fsck -f $3
    resize2fs $3
}

setup_mounts()
{
    mkdir -p $TARGET
    mount -L RKE2OS_STATE $TARGET

    if [ -e $TARGET/rke2os/system/growpart ]; then
        read DEV NUM < $TARGET/rke2os/system/growpart
        if [ ! -e "${DEV}${NUM}" ]; then
            # /dev/sda2 => /dev/sda2
            # /dev/nvme0n1p2 => /dev/nvme0n1p2
            PART=$(blkid -L RKE2OS_STATE)

            # /dev/sda2 => /dev/sda
            # /dev/nvme0n1p2 => /dev/nvme0n1
            DEV=$(echo "$PART" | sed -r 's/((\d+)p)?\d+$/\2/')

            # /dev/sda2 => 2
            # /dev/nvme0n1p2 => 2
            NUM=$(echo "$PART" | sed 's!.*[^0-9]!!')
        fi
        if [ -e "${PART:=${DEV}${NUM}}" ]; then
            umount $TARGET
            grow $DEV $NUM $PART || true
            mount -L RKE2OS_STATE $TARGET
        fi
        rm -f $TARGET/rke2os/system/growpart
    fi
}

setup_kernel_squashfs()
{
    KER_SRC="/.base/rke2os/system/kernel/$(uname -r)/kernel.squashfs"
    KER_DEST="$TARGET/rke2os/system/kernel/$(uname -r)/kernel.squashfs"
    if [ -e $KER_SRC ] && [ ! -e $KER_DEST ]; then
        mkdir -p $(dirname ${KER_DEST})
        cp -r $KER_SRC $KER_DEST
    fi
}

setup_rke2os()
{
    if [ -e $TARGET/rke2os/system/rke2os/current/rke2os ]; then
        return 0
    fi

    RKE2OS_SRC=/.base/rke2os/system/rke2os/current/rke2os
    RKE2OS_FILE=$TARGET/rke2os/system/rke2os/${VERSION_ID}/rke2os

    if [ ! -e ${RKE2OS_SRC} ]; then
        return 0
    fi

    if [ ! -e ${RKE2OS_FILE} ]; then
        mkdir -p $(dirname ${RKE2OS_FILE}.tmp)
        cp -f ${RKE2OS_SRC} ${K3OS_FILE}.tmp
        mv -f ${RKE2OS_FILE}.tmp ${K3OS_FILE}
    fi

    ln -sf ${VERSION_ID} $TARGET/rke2os/system/rke2os/current
}

setup_init()
{
    if [ -e $TARGET/sbin/init ]; then
        return 0
    fi

    mkdir -p $TARGET/sbin
    ln -sf ../rke2os/system/rke2os/current/rke2os $TARGET/sbin/init
}

setup_rke2()
{
    if [ -e $TARGET/rke2os/system/rke2/current/rke2 ]; then
        return 0
    fi

    for i in $(ls -drt $TARGET/rke2os/system/rke2/*); do
        if [ ! -L "$i" ]; then
            LATEST=$i
            break
        fi
    done

    if [ -e "${LATEST}" ]; then
        ln -sf $(basename "${LATEST}") $TARGET/rke2os/system/rke2/current
        return 0
    fi
}

takeover()
{
    if [ ! -e rke2os/system/takeover ]; then
        return 0
    fi

    touch rke2os/system/factory-reset

    if [ -L sbin ]; then
      rm -f sbin
    fi

    for i in *; do
        case $i in
            boot|rke2os|sbin)
                ;;
            *)
                rm -rf $i
        esac
    done
    for i in sbin/*; do
        case $i in
            sbin/init|sbin/rke2|sbin/rke2os)
                ;;
            *)
                rm -rf "$i"
        esac
    done

    rm -rf boot/[^g]*
    rm -f rke2os/system/takeover
    rm -rf rke2os/data
    sync
    
    if [ -e rke2os/system/poweroff ]; then
        rm -f rke2os/system/poweroff
        sync
        poweroff -f
    else
        reboot -f
    fi
}

setup_mounts
setup_rke2os
setup_kernel_squashfs
setup_init
setup_rke2

cd $TARGET

takeover || true

if [ -e rke2os/system/factory-reset ] || [ -e rke2os/system/ephemeral ]; then
    rm -rf rke2os/data rke2os/system/factory-reset
fi

losetup -d /dev/loop0 || true
mount --make-rprivate /
mkdir -p .root
pivot_root . .root
RKE2OS_MODE=local exec /sbin/init
