# See https://github.com/tomdb-be/rke2os/blob/master/README.md#configuration
# and https://github.com/tomdb-be/rke2os/blob/master/README.md#remastering-iso
# This file is a placeholder for custom configuration when building a custom ISO image.
