#!/bin/bash

. /etc/os-release
cat > issue << "BUNNY"

        /'))                _        ___   ____   _____
   _.--' // ___            | |      |__ ' / __ ' / ____|
  (  o    ''   ''.     _ __| | _____   ) | |  | | (___
  '.__ .'   '    '    | '__| |/ / _ \ / /| |  | |'___ '
   _/_/ /  _/    |_   | |  |   <  __// /_| |__| |____) |
  /_/__/'-/______/_}  |_|  |_|'_'___|____|'____/|_____/

BUNNY

cat >> /etc/issue << EOF
$PRETTY_NAME
Kernel \r on an \m (\l)

================================================================================
NIC              State          Address
$(ip -br addr show | grep -E -v '^(lo|flannel|cni|veth)')
================================================================================
EOF
cat >> /etc/issue << "EOF"

Welcome to rke2OS (login with user: rancher)
EOF
