#!/bin/bash
if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
    DIRTY="-dirty"
fi

COMMIT=$(git rev-parse --short HEAD)
GIT_TAG=${DRONE_TAG:-$(git tag -l --contains HEAD | head -n 1)}

if [[ -z "$DIRTY" && -n "$GIT_TAG" && -z "${VERSION}" ]]; then
    VERSION=$GIT_TAG
elif [ -z "${VERSION}" ]; then
    VERSION="$(git describe --always --tags)${DIRTY}"
fi

if [ -z "$ARCH" ]; then
    ARCH=$(go env GOHOSTARCH)
fi

if [ -z "$RKE2_VERSION" ]; then
    RKE2_VERSION=$VERSION
fi

TAG=${TAG:-"${VERSION}-linux-${ARCH}"}
REPO=${REPO:-rancher}
K3S_VERSION=${K3S_VERSION:-v1.21.4+k3s1}

if echo $TAG | grep -q dirty; then
    TAG=dev
fi
