#!/bin/bash

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
    DIRTY="-dirty"
fi

COMMIT=$(git rev-parse --short HEAD)
GIT_TAG=${DRONE_TAG:-$(git tag -l --contains HEAD | head -n 1)}

if [[ -z "$DIRTY" && -n "$GIT_TAG" && -z "$VERSION" ]]; then
    VERSION=$GIT_TAG
elif [ -z "$VERSION" ]; then
    VERSION="$(git describe --always --tags)${DIRTY}"
fi

if [ -z "$ARCH" ]; then
    ARCH=$(go env GOHOSTARCH)
fi

if [ -z "$RKE2_VERSION" ]; then
    RKE2_VERSION=${VERSION}
fi

TAG=${TAG:-"${VERSION}-${ARCH}"}
REPO=${REPO:-rancher}

if echo $TAG | grep -q dirty; then
    TAG=dev
fi
