#!/bin/bash
if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
    DIRTY="-dirty"
fi

COMMIT=$(git rev-parse --short HEAD)
GIT_TAG=${DRONE_TAG:-$(git tag -l --contains HEAD | head -n 1)}

if [[ -z "$DIRTY" && -n "$GIT_TAG" && -z "${VERSION}" ]]; then
    VERSION=$GIT_TAG
elif [ -z "${VERSION}" ]; then
    VERSION="$(git describe --always --tags)${DIRTY}"
fi

if [ -z "$ARCH" ]; then
    ARCH=$(go env GOHOSTARCH)
fi

TAG=${TAG:-"${VERSION}-linux-${ARCH}"}
REPO=${REPO:-tomdbbe}
GITREPO=${GITREPO:-"tomdb-be"}
K3S_VERSION=${K3S_VERSION:-v1.23.3+k3s1}
RKE2_VERSION=${RKE2_VERSION:-v1.23.3-multiarch-alpha1+rke2r1}

if echo $TAG | grep -q dirty; then
    TAG=dev
fi
